Máscara no InputGeneric
stellaoliveirabertt/PeoplePro pull request #25
Opened 2023-10-04 17:47 UTC by gloinho

# Máscara no InputGeneric

## Issues
- Fix #15 

## Checklist

- [x] Utilização de biblioteca [Maska](https://beholdr.github.io/maska/#/)
- [x] Inclusão de prop e directive no `InputGeneric.vue` para mascarar os valores

## Observações 
- Deixei dentro do `$emit` do `InputGeneric.vue` duas opções para serem emitidos os valores digitados para o componente pai:
```javascript
handleInput() {
            // Valor mascarado é enviado para o pai
            // this.$emit('update:modelValue', evt.target.value);
            // Valor sem máscara é enviado para o pai
            this.$emit('update:modelValue', this.bindedObject.unmasked);
```
- Solicito review @stellaoliveirabertt

2023-10-04 17:52 UTC, stellaoliveirabertt approved these changes

2023-10-04 18:56 UTC, jvricarte requested changes

2023-10-04 18:56 UTC, jvricarte commented on people-pro/src/components/InputGeneric.vue
> +            // Valor mascarado é enviado para o pai
Remover os comentários

2023-10-04 22:18 UTC, gloinho commented on people-pro/src/components/InputGeneric.vue
> +            // Valor mascarado é enviado para o pai
feito! commit 93cdc7d3938eef8ad7b76da082da0260203af8e6

2023-10-05 21:59 UTC, jvricarte approved these changes

2023-10-08 18:28 UTC, merged